#' Generates a pie plot (donut) that visualizes the relation between actually received and targeted number of submissions.
#'
#' The pie plot this function creates is generated by comparing the number of received submissions with the number of targeted submissions.
#' The target is calculated by multiplying the number-of-submissions goal per day times the number of days the data collection has been ongoing.
#' The number of days are determined using the function \code{\link{collection_period}}
#' If the targeted number of submissions has been exceeded the plot is all green and additionally provides the info by how many submissions the target number was exceeded.
#'
#' @param df Data frame that contains the data which is to be examined.
#' @param daily_submission_goal Integer or float that reflects the targeted number of daily submissions.
#'
#' @return Plotly html-widget
#'
#' @import plotly
#' @export
#'
#' @examples
submission_goal_donut <- function(df, daily_submission_goal){
  date_limits = repvisforODK::collection_period(df)
  date_diff = date_limits[[2]] - date_limits[[1]]

  submission_goal_total = as.numeric(date_diff)*daily_submission_goal
  submissions_total = nrow(df)
  submission_goal_deviation = submission_goal_total - submissions_total



  if (submission_goal_deviation>0){
    fig <- plotly::plot_ly(type='pie',
                           labels=c('Submisions received', 'Submissions missing'),
                           values=c(submissions_total, submission_goal_deviation),
                           textinfo='label+percent',
                           marker=list(colors=c('green', 'red')),
                           hole=0.4)

    fig <- fig %>% plotly::layout(title = paste0('Total number of submissions: Received vs. Target (', date_list[[2]], ')'),
                                  xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE, title='Test'),
                                  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
    return(fig)
  } else{
    fig <- plotly::plot_ly(type='pie',
                           labels=c('Submisions received'),
                           values=c(submissions_total),
                           textinfo='label+percent',
                           marker=list(colors=c('green', 'red')),
                           hole=0.4)

    fig <- fig %>% plotly::layout(title = paste0('Total number of submissions: Received vs. Target (', date_list[[2]], ')'),
                                  xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE, title='Test'),
                                  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                                  annotations=list(x=0.8, y=0.92,
                                                   xanchor='right',
                                                   showarrow=F,
                                                   font=list(color='orange'),
                                                   text=paste0('The target is currently exceeded by ',
                                                               abs(submission_goal_deviation),
                                                               ' submissions (',
                                                               round(abs(submission_goal_deviation)/submission_goal_total*100, 1),
                                                               ' %).')))
    return(fig)
  }
}
