#' Generates a pie plot (donut) that visualizes the relation between actually received and targeted number of submissions.
#'
#' The pie plot this function creates is generated by comparing the number of received submissions with the number of targeted submissions.
#' The target is calculated by multiplying the number-of-submissions goal per day times the number of days the data collection has been ongoing.
#' The number of days are determined using the function \code{\link{collection_period}}
#' If the targeted number of submissions has been exceeded the plot is all green and additionally provides the info by how many submissions the target number was exceeded.
#' Please note, that one and only one of the three data arguments (df, csv, svc) must be specified.
#'
#' @param df Data frame containing the ODK data that is to be used. Optional, defaults to NULL.
#' @param csv Character that specifies the path to the csv file that is to be read. Optional, defaults to NULL.
#' @param svc Logical that indicates whether the data shall be parsed using ruODK's \code{\link[ruODK]{odata_submission_get}}. Optional, defaults to FALSE.
#' @param daily_submission_goal Integer or float that reflects the targeted number of daily submissions.
#' @param date_col String that specifies the date or time stamp column in the data which is to be examined.
#' @param exclude_weekend Logical that determines whether weekends are excluded in the plot. Optional, defaults to TRUE.
#'
#' @return Plotly html-widget
#'
#' @import plotly lubridate
#' @export
#'
#' @examples
submission_goal_donut <- function(df = NULL, csv = NULL, svc = FALSE, daily_submission_goal, date_col, exclude_weekend = TRUE){

  df <- repvisforODK::check_data_args(df, csv, svc)

  if (daily_submission_goal < 0) {
    stop("The argument daily_submission_goal has to be defined as a positive integer or float.")
  }

  if (daily_submission_goal == 0) {
    warning("The argument daily_submission_goal is set to 0.")
  }

  # finding min and max date of the collection period
  date_limits = repvisforODK::collection_period(df = df, date_col = date_col)

  # calculating number of days of data collection period
  # first w/o weekend
  if (exclude_weekend) {

    all_wdays_in_period <- lubridate::wday(seq.Date(date_limits[[1]], date_limits[[2]], 'days'), abbr = TRUE)

    all_wdays_in_period_filtered <- all_wdays_in_period[!all_wdays_in_period %in% c(1, 7)]

    date_diff <- length(all_wdays_in_period_filtered)

  } else {
    # then with weekend
    date_diff = date_limits[[2]] - date_limits[[1]]
  }

  submission_goal_total = as.numeric(date_diff)*daily_submission_goal
  submissions_total = nrow(df)
  submission_goal_deviation = submission_goal_total - submissions_total



  if (submission_goal_deviation > 0){
    fig <- plotly::plot_ly(type='pie',
                           labels=c('Received', 'Missing'),
                           values=c(submissions_total, submission_goal_deviation),
                           textinfo='label+percent',
                           marker=list(colors=c(repvisforODK::set_color('green'), repvisforODK::set_color('red'))),
                           hole=0.4)

    fig <- fig %>% plotly::layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE, title='Test'),
                                  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
  } else{
    fig <- plotly::plot_ly(type='pie',
                           labels=c('Received'),
                           values=c(submissions_total),
                           textinfo='label+percent',
                           marker=list(colors=c(repvisforODK::set_color('green'), repvisforODK::set_color('red'))),
                           hole=0.4)

    fig <- fig %>% plotly::layout(xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE, title='Test'),
                                  yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                                  annotations=list(x=0.66, y=0.5,
                                                   xanchor='right',
                                                   showarrow=F,
                                                   font=list(color = repvisforODK::set_color('yellow')),
                                                   text=paste0('Target exceeded by: <br>',
                                                               round(abs(submission_goal_deviation), 0),
                                                               ' submissions (',
                                                               round(abs(submission_goal_deviation)/submission_goal_total*100, 1),
                                                               ' %)')))
  }

  # adding title to the html widget
  title <-  paste0('Total number of submissions: Received vs. Missing to Target (', date_limits[[2]], ')')
  fig <- repvisforODK::add_html_title_tag(fig, title)

  return(fig)
}
